// ZENTRO website app
const API = window.ZENTRO_CONFIG.API_BASE;
const CLIENT_ID = window.ZENTRO_CONFIG.DISCORD_CLIENT_ID;
const REDIRECT_URI = window.ZENTRO_CONFIG.REDIRECT_URI;
async function api(path) { const r = await fetch(API + path); if (!r.ok) throw new Error('API error'); return r.json(); }
function getToken() { const h = new URLSearchParams(location.hash.slice(1)); const t = h.get('access_token'); if (t) { localStorage.setItem('zt', t); history.replaceState(null, '', location.pathname); } return localStorage.getItem('zt') || localStorage.getItem('discord_token'); }
async function getDiscordUser() { const t = getToken(); if (!t) return null; const r = await fetch('https://discord.com/api/users/@me', { headers: { Authorization: 'Bearer ' + t } }); if (!r.ok) { localStorage.removeItem('zt'); localStorage.removeItem('discord_token'); return null; } return r.json(); }
function login() { location.href = 'https://discord.com/oauth2/authorize?client_id=' + CLIENT_ID + '&redirect_uri=' + encodeURIComponent(REDIRECT_URI) + '&response_type=token&scope=identify'; }
function logout() { localStorage.removeItem('zt'); localStorage.removeItem('discord_token'); location.href = '/'; }
function fmt(n) { return Number(n || 0).toLocaleString(); }
function fmtDate(t) { return new Date(t).toLocaleString('ar-EG'); }
function avatar(u) { return u.avatar ? `https://cdn.discordapp.com/avatars/${u.id}/${u.avatar}.png?size=128` : 'https://cdn.discordapp.com/embed/avatars/0.png'; }
async function loadStats() { try { const s = await api('/api/stats'); stat-users.textContent = fmt(s.users); stat-coins.textContent = fmt(s.totalCoins); stat-transfers.textContent = fmt(s.transfers); stat-status.textContent = s.botStatus; } catch(e) { stat-status.textContent = 'API unavailable'; } }
async function loadTopPreview() { try { const d = await api('/api/leaderboard'); top-preview.innerHTML = d.leaderboard.slice(0, 10).map((u, i) => `<div class=row><span>#${i+1}</span><span>${u.user_id}</span><span>${fmt(u.total)} ZC</span></div>`).join(''); } catch(e) { top-preview.innerHTML = '<div class=empty>تعذر تحميل الترتيب</div>'; } }
async function loadProfile() { const u = await getDiscordUser(); if (!u) { login-box.style.display = 'block'; profile-box.style.display = 'none'; return; } login-box.style.display = 'none'; profile-box.style.display = 'block'; avatar.src = avatar(u); username.textContent = u.global_name || u.username; userid.textContent = u.id; try { const p = await api('/api/user/' + u.id); wallet.textContent = fmt(p.balance) + ' ZC'; bank.textContent = fmt(p.bank) + ' ZC'; total.textContent = fmt(p.totalCoins) + ' ZC'; sent.textContent = p.transfersSent; received.textContent = p.transfersReceived; transfers.textContent = p.transfersTotal; xp.textContent = fmt(p.xp) + ' XP'; rank.textContent = '#' + p.wealthRank; } catch(e) {} try { const t = await api('/api/transactions/' + u.id); transactions.innerHTML = t.transactions.length ? t.transactions.map(x => `<div class="tx ${x.type}"><span>${x.type === 'sent' ? 'حوّلت إلى' : 'استلمت من'} ${x.type === 'sent' ? x.receiver_id : x.sender_id}</span><span>${fmt(x.amount)} ZC</span><span>${fmtDate(x.created_at)}</span></div>`).join('') : '<div class=empty>لسه معندكش تحويلات</div>'; } catch(e) { transactions.innerHTML = '<div class=empty>تعذر تحميل التحويلات</div>'; } }
async function loadLeaderboard() { try { const d = await api('/api/leaderboard'); leaderboard.innerHTML = d.leaderboard.map((u, i) => `<div class="lb-row ${i===0?'gold':i===1?'silver':i===2?'bronze':''}"><span>#${i+1}</span><span>${u.user_id}</span><span>${fmt(u.total)} ZC</span></div>`).join(''); const u = await getDiscordUser(); if (u) { const me = await api('/api/user/' + u.id); const inTop = d.leaderboard.some(x => x.user_id === u.id); my-rank.textContent = inTop ? 'أنت داخل Top 100' : 'ترتيبك: #' + me.wealthRank; } } catch(e) { leaderboard.innerHTML = '<div class=empty>تعذر تحميل الترتيب</div>'; } }