const state={wallet:1240,bank:3600,history:[{type:'in',user:'Nour',amount:250,date:'اليوم'},{type:'out',user:'Omar',amount:120,date:'أمس'},{type:'in',user:'Sara',amount:500,date:'أمس'}],top:[{name:'Nour',amount:18450},{name:'Omar',amount:15230},{name:'Sara',amount:12980},{name:'Ali',amount:9450},{name:'Lina',amount:8120}]};
const params=new URLSearchParams(location.hash.slice(1));const token=params.get('access_token');
if(token){fetch('https://discord.com/api/users/@me',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json()).then(u=>{document.querySelectorAll('#user-name,#profile-name').forEach(e=>e.textContent=u.global_name||u.username);document.querySelectorAll('#user-avatar,#profile-avatar').forEach(e=>e.src=u.avatar?'https://cdn.discordapp.com/avatars/'+u.id+'/'+u.avatar+'.png?size=128':'https://cdn.discordapp.com/embed/avatars/0.png');document.getElementById('profile-id').textContent='ID: '+u.id}).catch(()=>{});history.replaceState(null,'',location.pathname)}
function render(){document.getElementById('wallet').textContent=state.wallet.toLocaleString();document.getElementById('bank').textContent=state.bank.toLocaleString();document.getElementById('total').textContent=(state.wallet+state.bank).toLocaleString();document.getElementById('history-list').innerHTML=state.history.map(h=>`<li><span>${h.type==='in'?'استلام من':'إرسال إلى'} <b>${h.user}</b><small>${h.date}</small></span><span class="${h.type==='in'?'amount-in':'amount-out'}">${h.type==='in'?'+':'-'}${h.amount} ZC</span></li>`).join('');document.getElementById('top-list').innerHTML=state.top.map((u,i)=>`<li><span class="rank ${i===0?'first':i===1?'second':i===2?'third':''}">${i+1}</span><b>${u.name}</b><span>${u.amount.toLocaleString()} ZC</span></li>`).join('')}
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById(t.dataset.tab).classList.add('active')}));
document.getElementById('claim-daily').addEventListener('click',()=>{state.wallet+=250;state.history.unshift({type:'in',user:'المكافأة اليومية',amount:250,date:'الآن'});render();document.getElementById('daily-status').textContent='تم استلام 250 ZC'});
document.getElementById('send-transfer').addEventListener('click',()=>{const user=document.getElementById('transfer-user').value.trim();const amount=Number(document.getElementById('transfer-amount').value);if(!user||!amount||amount<1){document.getElementById('transfer-status').textContent='اكتب اسم المستخدم وعدد ZC صحيح';return}if(amount>state.wallet){document.getElementById('transfer-status').textContent='رصيد المحفظة غير كافٍ';return}state.wallet-=amount;state.history.unshift({type:'out',user,amount,date:'الآن'});render();document.getElementById('transfer-status').textContent='تم إرسال '+amount+' ZC إلى '+user});
document.getElementById('deposit').addEventListener('click',()=>{const amount=Math.min(100,state.wallet);state.wallet-=amount;state.bank+=amount;render()});
document.getElementById('withdraw').addEventListener('click',()=>{const amount=Math.min(100,state.bank);state.bank-=amount;state.wallet+=amount;render()});
document.getElementById('logout').addEventListener('click',()=>location.href='index.html');
render()