async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});return r.json()}
async function load(){const d=await api('/api/me');if(d.guest){document.getElementById('userName').textContent='زائر';return}
document.getElementById('userAvatar').src=d.user.avatar||'';document.getElementById('userName').textContent=d.user.username;document.getElementById('wallet').textContent=d.user.wallet+' ZC';document.getElementById('bank').textContent=d.user.bank+' ZC';document.getElementById('total').textContent=d.total+' ZC';document.getElementById('streakDays').textContent=d.user.streak;
const tx=document.getElementById('txList');tx.innerHTML=d.transactions.map(t=>`<li>${t.sender} → ${t.receiver}: ${t.amount} ZC</li>`).join('')||'<li>لا يوجد تحويلات</li>';
const top=await api('/api/top');document.getElementById('topList').innerHTML=top.map((u,i)=>`<li>${i+1}. ${u.username} — ${u.total} ZC</li>`).join('')}
document.getElementById('dailyBtn')?.addEventListener('click',async()=>{const r=await api('/api/daily',{method:'POST'});alert(r.ok?'تم استلام 250 ZC':'غير متاح الآن');load()});
document.getElementById('transferBtn')?.addEventListener('click',async()=>{const r=await api('/api/transfer',{method:'POST',body:JSON.stringify({username:document.getElementById('transferName').value,amount:document.getElementById('transferAmount').value})});alert(r.ok?'تم التحويل':'فشل التحويل');load()});
document.getElementById('depositBtn')?.addEventListener('click',async()=>{await api('/api/bank',{method:'POST',body:JSON.stringify({action:'deposit',amount:100})});load()});
document.getElementById('withdrawBtn')?.addEventListener('click',async()=>{await api('/api/bank',{method:'POST',body:JSON.stringify({action:'withdraw',amount:100})});load()});
load();